### ISSUE TITLE
A few ques

### ISSUE THREAD

**Issue by mingust** [OHNLP/Backbone#13]
Hi 

I followed the readme to download the latest version of OHNLP but that points me to  Backabone.zip but there is no longer any run_win.bat there. Please let me have some updated instructions.

Also the Covid19 folder under resources (Covid19 rules) had removed...

**Comment by qqndrew** [comment]
You are probably looking for the MedTagger project. I am unsure what instruction set you are following, there are several floating around out there depending on the project for which the instructions were created.

If you are actually intending to install backbone, please use the install script located at https://github.com/OHNLP/OHNLPTK_SETUP which will download/install everything at the correct location for you.

COVID-19 ruleset has been merged with PASC ruleset for the MedTagger project.

**Comment by mingust** [comment]
Thanks the info, will give it a go.

From the setup script seems you guy develop on Linux environment..
I should install on Linux also...sometimes it is a pain to adopt another environment that differs from the developers.
________________________________

**Comment by qqndrew** [comment]
For what it is worth, we do testing against all three major OSes and it works fine
- Windows (via a Ubuntu installation on WSL)
- Mac OSX
- Linux (Debian and Ubuntu)

Testing is done against Java 17 although anything Java 11+ should work (recommend 13 at a minimum though due to JDK11 being EOL and the modularization rework)

**Comment by mingust** [comment]
I think I installed ok.

When I run it (i.e. run_pipeline_local.sh), it list out 5 choices, what shall I do for a quick run (making sure it works).
________________________________

**Comment by qqndrew** [comment]
So it really depends on what you are trying to do.
You'll probably want to ./run_backbone_configurator.sh first and edit a pipeline. This repository (Backbone/OHNLPTK) is for setting up ETL pipelines (including NLP) at scale. If you are just wanting to run the NLP engine itself probably just run medtagger directly instead (see my response to your other issue instead)

**Comment by mingust** [comment]
Hi Andrew,

I tried to run_medtaggerunix_mac.sh ...
Now I am working on Linux
There is no error message (apart from Java messages) but no icon(or user menu) appears...?

________________________________

**Comment by qqndrew** [comment]
run_medtagger_unix_mac.sh is for a direct run via CLI using the supplied arguments and does not display a UI.

**Comment by mingust** [comment]
Hi Andrew,

Ok, I see.
Now, I ran maven build successfully, finally ant dist seem outdated (recent ant version make changes).

On windows platform, shall I use an older version of ant (same as yours)? Or any alternatives?

Thanks again.

________________________________

**Comment by qqndrew** [comment]
Ant should be up to date/is the same version that github actions uses.
Is there any reason you are building from source instead of using the release? If you are not making code changes may be easier to just use the release compiled versions.

**Comment by mingust** [comment]
Hi Andrew,

I followed the instructions to build without error, with a jar output.
But the jar file can't run.

Your instructions seems only have a few lines, please provide more details.
Thanks,
________________________________
